### ISSUE TITLE
ROADMAP - Dedicated Diary/Journal function

### ISSUE THREAD

**Issue by iandstanley** [Standard-Unix-Notes/unix-notes#6]
ROADMAP feature

**Comment by iandstanley** [comment]
Whilst coding other functionality I thought it might be good to have a journal/diary function

My Idea would be to have a separate command (or subcommand) that writes to a specified notebook 'journal'

- [ ] Do I want to have subdirectories by year?
- [ ] and subdirectories by month?
- [ ] Each call to the function should append to the current dates (or months??) note
- [ ] Each call should datestamp the end of the notes file ready for the user to just append

**Comment by iandstanley** [comment]
How do I want to do the viewing of the journal ???

**Comment by iandstanley** [comment]
completed in release 2.0
